apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: eu.gcr.io/woven-computing-234012/example-voting-app/result:{{ .Chart.AppVersion }}
        name: result
