apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: docker.pro.harbur.io/example-voting-app-vote:{{ .Chart.AppVersion }}
        name: vote
