apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: eu.gcr.io/woven-computing-234012/example-voting-app/vote:{{ .Chart.AppVersion }}
        name: vote
