apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: eu.gcr.io/woven-computing-234012/example-voting-app/worker:{{ .Chart.AppVersion }}
        name: worker
