dependencies:
  - name: example-voting-app-vote
    version: 0.1.0
    repository: "@chartmuseum"
  - name: example-voting-app-result
    version: 0.1.0
    repository: "@chartmuseum"
  - name: example-voting-app-worker
    version: 0.1.0
    repository: "@chartmuseum"
  - name: redis
    version: 9.1.3
    repository: "@stable"
