name: CI

on:
  push:
    branches:
    - master

jobs:

  create-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: echo -n $GCLOUD_AUTH | base64 --decode | docker login -u _json_key --password-stdin https://eu.gcr.io/woven-computing-234012
    - name: Build & Push the Docker images
      run: |
        docker-compose build
        docker-compose push

  create-charts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Helm Init
      run: helm init -c
    - name: Setup Repositories
      env:
        HELM_USERNAME: ${{ secrets.HELM_USERNAME }}
        HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
      run: helm repo add chartmuseum https://chartmuseum.pro.harbur.io --username $HELM_USERNAME --password $HELM_PASSWORD
    - name: Install Helm Push Plugin
      run: helm plugin install https://github.com/chartmuseum/helm-push
    - name: Pushes Charts
      run: |
        for folder in charts/*/; do
          helm push $folder chartmuseum
        done
  create-releases:
    runs-on: ubuntu-latest
    needs:
    - create-images
    - create-charts
    steps:
    - uses: actions/checkout@v1
    - name: GCloud Authenatication
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "$GCLOUD_AUTH" | base64 --decode > "$HOME"/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project woven-computing-234012
        gcloud container clusters get-credentials internal -z europe-west1-b
    - name: Setup Repositories
      env:
        HELM_USERNAME: ${{ secrets.HELM_USERNAME }}
        HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
      run: |
        helm init -c
        helm repo add chartmuseum https://chartmuseum.pro.harbur.io --username $HELM_USERNAME --password $HELM_PASSWORD
    - name: Upgrade Release
      run: |
        helm upgrade example-voting-app-dev charts/example-voting-app
